### ISSUE TITLE
Should `store` typed `Effect (CalledParamsStore params)` instead?

### ISSUE THREAD

**Issue by wewei** [pujoheadsoft/purescript-pmock#1]
It's great to have an open source PureScript mocking library! Well I'm trying it our, I find the `mock` function is declared without side effect. However, the `Mock` itself is a stateful type (the invocation sequence). I think the root cause is the FFI function `store` is declared as `Unit -> CalledParamsStore params`, but the implementation is impure

```purescript
foreign import store :: forall params. Unit -> CalledParamsStore params -- Declared as pure

type CalledParamsStore params = {
  calledParamsList :: CalledParamsList params,
  store :: params -> Unit -- Declared as pure
}
```

```js
export const store = function(_) {
  const calledParamsList = []; // Side effect
  const storeCalledParams = function(params) {
    calledParamsList.push(params); // Side effect
  }
  return {
    calledParamsList,
    store: storeCalledParams
  }
}
```

Would it be better if we change it into

 ```purescript
foreign import store :: forall params. Effect (CalledParamsStore params)

type CalledParamsStore params = {
  calledParamsList :: CalledParamsList params,
  store :: params -> Effect Unit
}
```

```js
export const store = function() {
  const calledParamsList = [];
  const storeCalledParams = function(params) {
    return () => calledParamsList.push(params);
  }
  return {
    calledParamsList,
    store: storeCalledParams
  }
}
```

**Comment by pujoheadsoft** [comment]
Thank you for the comment!
I think you are right, so I'll see if I can't make it work.

**Comment by pujoheadsoft** [comment]
I've made the following revisions.
- Changed the definition of the FFI function.
- Added a MonadEffect constraint to mock functions.

When the README is modfied, I'll proceed with the release.

**Comment by pujoheadsoft** [comment]
I'll close it now that the release is complete.
Thank you for giving me the issue.

**Comment by wewei** [comment]
Wow! That's really a quick turn around! Thanks for the fix!
